### ISSUE TITLE
stats for Natasha's pitch

### ISSUE THREAD

**Issue by Carmer** [vangst/planning#1]
Natasha requested stats for a pitch: 

https://docs.google.com/presentation/d/1hqec9R7WHyx6HaVdvEKSjjD-3BqUq-yu/edit?disco=AAAApj0FXlA&usp_dm=false#slide=id.p1

The only requested stat is : 

- [x] How many total users saw vangst.com in 2022
- [ ] anything else we feel would be valuable
- [ ]

**Comment by scottdavis** [comment]
Delivered GA data to natasha
